image: Visual Studio 2015

environment:
  MSVC_DEFAULT_OPTIONS: ON
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  GENERATOR: Ninja
  MAKE_PROGRAM: ninja
  
cache: 
- build\curl-install\ -> appveyor.yml
- build\libressl-install\ -> appveyor.yml
- build\zlib-install\ -> appveyor.yml
- build\thirdparty\civetweb-1.10 -> appveyor.yml
- build\thirdparty\cxxopts -> appveyor.yml
- build\thirdparty\rocksdb -> appveyor.yml
- build\thirdparty\ -> appveyor.yml
- build\thirdparty\yaml-cpp-yaml-cpp-20171024 -> appveyor.yml

clone_folder: C:\projects\nifi-minifi-cpp
  
build_script:
   - cd C:\projects\nifi-minifi-cpp
   - mkdir build & exit 0
   - cd build
   - cmake -g"Ninja" -DWIN32=WIN32 -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_OFF=OFF -DDISABLE_CONTROLLER=OFF -DUSE_SYSTEM_OPENSSL=OFF -DUSE_SYSTEM_CURL=OFF -DUSE_SYSTEM_ZLIB=OFF -DFORCE_WINDOWS=ON -DUSE_SYSTEM_UUID=OFF -DDISABLE_LIBARCHIVE=ON -DDISABLE_SCRIPTING=ON -DEXCLUDE_BOOST=ON -DENABLE_WEL=TRUE .. 
   - set msbuild_platform=x64 
   - msbuild nifi-minifi-cpp.sln
   - ctest -C Debug
